name: CI server

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_TAG_SERVER: server

jobs:
  build:
    name: Server - Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build the Docker image
        run: docker build -t $IMAGE_TAG_SERVER --target=create-build .
      - name: Run Prettier
        run: docker run $IMAGE_TAG_SERVER sh -c 'npm run format:verify'
      - name: Run ESLint
        run: docker run $IMAGE_TAG_SERVER sh -c 'npm run lint:verify'
      - name: Run tests
        run: docker run -v ./coverage:/user/src/app/server/coverage $IMAGE_TAG_SERVER sh -c 'npm run test:cov'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
