name: CI server

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_TAG_SERVER: server

jobs:
  build:
    name: Server - Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build the Docker image
        run: docker build -t $IMAGE_TAG_SERVER --target=create-build .
      - name: Run Prettier
        run: docker run $IMAGE_TAG_SERVER sh -c 'npm run format:verify'
      - name: Run ESLint
        run: docker run $IMAGE_TAG_SERVER sh -c 'npm run lint:verify'
      - name: Run tests
        run: docker run $IMAGE_TAG_SERVER sh -c 'npm run test:cov'
      - name: Check coverage directory existence
        run: ls coverage/
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload SonarCloud Coverage
        run: docker run \
                --rm \
                -e SONAR_HOST_URL="http://${{ secrets.SONAR_HOST_URL }}" \
                -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}" \
                -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
                -v ./src/:/usr/src \
                sonarsource/sonar-scanner-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
