name: CI

on: [pull_request]

env:
  IMAGE_TAG_SERVER: server
  IMAGE_TAG_WEB: web
  IMAGE_TAG_MOBILE: mobile

jobs:
  ci_server:
    name: Server - Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        working-directory: ./server
        run: docker build -t $IMAGE_TAG_SERVER --target=create-build .

      - name: Run Prettier
        working-directory: ./server
        run: docker run $IMAGE_TAG_SERVER sh -c 'npm run format:verify'

      - name: Run ESLint
        working-directory: ./server
        run: docker run $IMAGE_TAG_SERVER sh -c 'npm run lint'

      - name: Run tests
        working-directory: ./server
        run: docker run $IMAGE_TAG_SERVER sh -c 'npm run test'
  ci_web:
    needs: ci_server
    name: Web - Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        working-directory: ./web
        run: docker build -t $IMAGE_TAG_WEB --target=create-build .

      - name: Run Prettier
        working-directory: ./web
        run: docker run $IMAGE_TAG_WEB sh -c 'npm run format:verify'

      - name: Run ESLint
        working-directory: ./web
        run: docker run $IMAGE_TAG_WEB sh -c 'npm run lint'

      - name: Run tests
        working-directory: ./web
        run: docker run $IMAGE_TAG_WEB sh -c 'npm run test:nowatch'
  ci_mobile:
    needs: ci_server
    name: Mobile - Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        working-directory: ./mobile
        run: docker build -t $IMAGE_TAG_MOBILE --target=create-build .

      - name: Run Prettier
        working-directory: ./mobile
        run: docker run $IMAGE_TAG_MOBILE sh -c 'npm run format:verify'

      - name: Run ESLint
        working-directory: ./mobile
        run: docker run $IMAGE_TAG_MOBILE sh -c 'npm run lint'

      - name: Run tests
        working-directory: ./mobile
        run: docker run $IMAGE_TAG_MOBILE sh -c 'npm run test'
